language: node_js
node_js:
  - '8'

cache:
  yarn: true
  directories:
  - node_modules

env:
  - TEST_SUITE=misc
  - TEST_SUITE=unit
  - TEST_SUITE=unit-each
  - TEST_SUITE=a11y

dist: trusty

addons:
  apt:
    packages:
      - google-chrome-stable
  firefox: 'latest-esr'

matrix:
  exclude:
  - env: TEST_SUITE=unit-each
  allow_failures:
  - env: TEST_SUITE=unit-each
  - env: TEST_SUITE=a11y

before_install:
  - if [[ -n "${AAT_TOKEN}" ]]; then sed -e "s|\${AAT_TOKEN}|$AAT_TOKEN|g" < .aat.yml.src > .aat.yml; fi
  - tar -xjf /tmp/firefox-latest-esr.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH"
  - export CHROME_BIN=google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - yarn install || (cat yarn-debug.log; false)
  - if [[ -n "${AAT_TOKEN}" && "$TEST_SUITE" == "a11y" ]]; then yarn add https://aat.mybluemix.net/dist/karma-ibma.tgz; fi

script:
  - if [[ "$TEST_SUITE" == "misc" ]]; then yarn lint; fi
  - if [[ "$TEST_SUITE" == "misc" ]]; then yarn build; fi
  - if [[ "$TEST_SUITE" == "unit" ]]; then yarn test:unit -- -b ChromeHeadless_Travis -b Firefox; fi
  - if [[ "$TEST_SUITE" == "unit-each" ]]; then find tests/spec -name "*.js" ! -name left-nav_spec.js -print0 | xargs -0 -n 1 -P 1 yarn test:unit -- -d -f; fi
  - if [[ -n "${AAT_TOKEN}" && "$TEST_SUITE" == "a11y" ]]; then yarn test:a11y; fi

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
